/**
 * Turns the deployment overlay's declared policy into the SQL that makes it
 * real.
 *
 *     npm run settings:sql                 # print the statement
 *     npm run settings:sql -- --check      # exit 1 if the file is invalid
 *     npm run settings:sql -- --json       # print the policy as jsonb only
 *
 * MFA is enforced in Postgres — a restrictive RLS policy on every table calls
 * `public.mfa_satisfied()`, which reads `security_policies.mfa_policy`. A
 * setting that stayed in the bundle would gate the SPA and nothing else. So
 * the declaration in `deployment/settings.json` has to be applied to the
 * database, and this is what turns one into the other.
 *
 * Applying it is the deployment repository's job: this repository deploys
 * nowhere and holds no credentials. Pipe the output into `psql`, or paste it
 * into the Supabase SQL editor:
 *
 *     npm run --silent settings:sql | psql "$DATABASE_URL"
 *
 * `--check` validates without printing SQL, so a pipeline can fail on a
 * malformed policy before it reaches a migration step. It deliberately does
 * *not* compare against a live database — that would need credentials this
 * repository must not have. The live-versus-declared comparison is
 * `mfa_policy_effective()`, surfaced on the super-admin version page.
 */

import { readFileSync } from "fs";
import path from "path";

import {
  defineSettings,
  mfaPolicyRow,
  validateSettings,
} from "../src/deployment/settings.ts";
import { resolveDeploymentDir } from "./deployment-dir.ts";

// Explicit `.ts` extensions and `import.meta.dirname`: this file runs under
// node --experimental-strip-types, which strips types without rewriting
// specifiers, and the package is ESM so there is no __dirname.
const root = path.resolve(import.meta.dirname, "..");
const deploymentDir = resolveDeploymentDir(root, process.env.NODE_ENV ?? "production");
const settingsFile = path.join(deploymentDir, "settings.json");

const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");
const jsonOnly = args.has("--json");

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

let raw: unknown;
try {
  raw = JSON.parse(readFileSync(settingsFile, "utf8"));
} catch (error) {
  // An overlay with no settings.json is valid — it means "use the defaults" —
  // but a malformed one is a typo the operator needs to see, not something to
  // silently paper over with a policy they did not choose.
  const code = (error as { code?: string }).code;
  if (code === "ENOENT") {
    process.stderr.write(
      `[settings] no ${settingsFile}; using the built-in defaults\n`,
    );
    raw = {};
  } else {
    fail(`[settings] ${settingsFile} is not valid JSON: ${(error as Error).message}`);
  }
}

const problems = validateSettings(raw);
if (problems.length > 0) {
  fail(
    [`[settings] ${settingsFile} is not a usable policy:`, ...problems.map((p) => `  - ${p}`)].join(
      "\n",
    ),
  );
}

const policy = mfaPolicyRow(defineSettings(raw as Parameters<typeof defineSettings>[0]));
const policyJson = JSON.stringify(policy, null, 2);

if (checkOnly) {
  const roles = Object.keys(policy);
  process.stderr.write(
    `[settings] ok — MFA enforced for: ${roles.length ? roles.join(", ") : "(nobody)"}\n`,
  );
  process.exit(0);
}

if (jsonOnly) {
  process.stdout.write(`${policyJson}\n`);
  process.exit(0);
}

/**
 * Single-quotes doubled for SQL. The policy is machine-generated from a
 * validated object whose keys are a fixed role list and whose values are
 * ISO instants, so there is nothing here that can carry a quote — but the
 * statement gets pasted into consoles by hand, and an emitter that only
 * happens to be safe is not.
 */
const literal = policyJson.replace(/'/g, "''");

process.stdout.write(`-- Generated by \`npm run settings:sql\` from:
--   ${path.relative(root, settingsFile)}
--
-- Applies the declared MFA policy. Role -> enforcement start; null means
-- immediately. A role absent from the object is not required to enrol.
--
-- Re-running this is safe and idempotent. Removing a role takes effect at
-- once: anyone who enrolled stays enrolled, they are simply no longer
-- required to be.
INSERT INTO public.security_policies (key, value)
VALUES ('mfa_policy', '${literal}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Read it back, so applying this in a console shows what took effect.
SELECT value AS mfa_policy FROM public.security_policies WHERE key = 'mfa_policy';
`);
